server:
  port: 8084

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:1234}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}}
      database: ${MONGO_DB:notification_service}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/twitter
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        default-requeue-rejected: false
  sendgrid:
    api-key: ${SENDGRID_API_KEY:SG.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
    from-email: ${SENDGRID_FROM_EMAIL:noreply@penguninn.com}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  services:
    follow-service:
      url: http://localhost:8086
    tweet-service:
      url: http://localhost:8083
    comment-service:
      url: http://localhost:8085
  rabbitmq:
    exchange:
      identity-events: identity.events.exchange
      follow-events: follow.events.exchange
      tweet-events: tweet.events.exchange
      comment-events: comment.events.exchange
    queue:
      user-registered: notification.registered.queue
      followed: notification.followed.queue
      tweet-created: notification.tweet.queue
      tweet-liked: notification.tweet.liked.queue
      comment-created: notification.comment.created.queue
    routing-key:
      user-registered: identity.event.registered
      followed: follow.event.followed
      tweet-created: tweet.event.created
      tweet-liked: tweet.event.liked
      comment-created: comment.event.created
  firebase:
    config-file: firebase/firebase-admin-sdk.json


management:
  endpoints:
    web:
      exposure:
        include: [ "health", "routes", "metrics", "info" ]
  info:
    env:
      enabled: true
info:
  app:
    name: notification-service

#logging:
#  level:
#    org.springframework.web: debug
#    org.springframework.security: debug
#    org.springframework.security.web: debug
#    org.springframework.web.cors: debug
#    org.springframework.web.filter.CorsFilter: debug
