server:
  port: 8087

spring:
  application:
    name: timeline-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:1234}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}}
      database: ${MONGO_DB:timeline_service}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/twitter
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        default-requeue-rejected: false
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  services:
    tweet-service:
      url: http://localhost:8083
    follow-service:
      url: http://localhost:8086
  rabbitmq:
    exchange:
      tweet-events: tweet.events.exchange
      follow-events: follow.events.exchange
    queue:
      tweet-created: timeline.tweet.queue
      followed: timeline.followed.queue
      unfollowed: timeline.unfollowed.queue
    routing-key:
      tweet-created: tweet.event.created
      followed: follow.event.followed
      unfollowed: follow.event.unfollowed

management:
  endpoints:
    web:
      exposure:
        include: ["health", "routes", "metrics", "info"]
  info:
    env:
      enabled: true
info:
  app:
    name: timeline-service

#logging:
#  level:
#    org.springframework.web: debug
#    org.springframework.security: debug
#    org.springframework.security.web: debug
#    org.springframework.web.cors: debug
#    org.springframework.web.filter.CorsFilter: debug