spring:
  application:
    name: timeline-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      name: timeline-service