spring:
  application:
    name: registry-service
  profiles:
    active: native
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      name: registry-service