server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#        git:
#          uri:
#          clone-on-start: true
#          default-label: main
#          username:
#          password:

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "env", "refresh"]

#logging:
#  level:
#    org.springframework.cloud.config: debug