server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/penguninn/social-app-config.git
          clone-on-start: true
          default-label: main
          username: penguninn
          password: ${GITHUB_TOKEN}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "env", "refresh"]

#logging:
#  level:
#    org.springframework.cloud.config: debug