server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/penguninn/social-app-config.git
          clone-on-start: true
          default-label: main
          username: penguninn
          password: ${GITHUB_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "env", "refresh"]

logging:
  level:
    org.springframework.cloud.config: debug